# Generated by Django 3.0 on 2021-07-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('company_name', models.CharField(default=None, max_length=150)),
                ('bike_name', models.CharField(default=None, max_length=100)),
                ('bike_message', models.TextField()),
                ('deliver_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
