# Generated by Django 3.0 on 2021-06-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_auto_20210624_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
