# Generated by Django 3.0 on 2021-09-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scale',
            old_name='scale_tpe',
            new_name='scale_type',
        ),
    ]
