# Generated by Django 3.0 on 2021-09-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_auto_20210920_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scale',
            new_name='Student',
        ),
    ]
