# Generated by Django 3.0 on 2021-09-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('branch', models.CharField(max_length=250)),
                ('medeam', models.BooleanField(default=True)),
                ('pass_date', models.DateField()),
            ],
        ),
    ]
