# Generated by Django 3.0 on 2021-09-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pass_date',
        ),
    ]
